sample_rate: 16000
feat_type: wav  # wav, fbank

# model
model_name: whisper
model_conf:
  n_mels: 128
  n_audio_ctx: 1500
  n_audio_state: 1280
  n_audio_head: 20
  n_audio_layer: 32
  ckpt: Whisper/large-v3/encoder.pt
  feat_aggre: mean_pool
  freeze_encoder: True

# inference
batch_size: 32
