sample_rate: 16000
feat_type: wav  # wav, fbank

# model
model_name: whisper
model_conf:
  n_mels: 80
  n_audio_ctx: 1500
  n_audio_state: 768
  n_audio_head: 12
  n_audio_layer: 12
  ckpt: Whisper/small/encoder.pt
  feat_aggre: mean_pool
  freeze_encoder: True

# inference
batch_size: 32
