# path
meta_data_dir: data/meta_data
detect_conf_dir: uni_detect/conf/

# datasets
downstream: idmt_air
ds_type: ng
infer_metric: knn  # classify, knn
test_size: 0.5
split_level: ori  # ori, seg

# data
input_duration: 10.0
hop_duration: null  # None
comple: pad  # pad, cycle
sample_rate: null
feat_type: null
use_shard: False

# preprocess
norm: False

# model
model_name: null
with_loss: False
aggregation: mean
emb_size: 0

# inference
batch_size: 8

# detect
detect:
  k: 5
