# path
meta_data_dir: data/meta_data
detect_conf_dir: uni_detect/conf/

# datasets
downstream: umged_vol
ds_type: ng
infer_metric: knn  # classify, knn
lab: scene_E  # scene_E, scene_G
test_size: null
split_level: ori

# data
input_duration: 10.0
hop_duration: null  # None
comple: pad  # pad, cycle
sample_rate: null
feat_type: null
use_shard: False

# preprocess
norm: False

# model
model_name: null
with_loss: False
aggregation: mean
emb_size: 0

# inference
batch_size: 10

# detect
detect:
  k: 5

# multi split
multi_split_conf:
  min_test_size: 0.05
  max_test_size: 0.95
  delta: 0.05
